### ISSUE TITLE
Implement contents of super secret menu

### ISSUE THREAD

**Issue by tspopp** [tspopp/AquaMQTT#17]
It seems there is another super secret menu within the HMI controller, when holding MENU and turning the wheel left and then right. This leads to another `Diagnostics` menu appearing, which I previously did not know 😵‍💫 [Source](https://gathering.tweakers.net/forum/list_message/73439340#73439340)

- Advanced Settings
  - ✅  Volume (270l / 200l) 
  - ✅ PWM Speeds 1,2,3 (65%, 81%, 100%)
  - ✅ Brand Setting (NoName, Sauter, Atlantic, Thermor)
  - ✅ Heat-Exchanger (Yes/No)
  - ✅  External Communication (Yes/No)
  - ✅  Circulation (Yes/No)
  - ✅  PV-Input (Yes/No)
  - ✅  Min T° Target
  - ✅ Anti-Trockenheizung (Yes/No)
  - ✅ Elec Backup Power (1600W, 1700W, 1800W,...) 

- Errors
  - ✅ Parse Error Messages
  - ✅ Identify Error Request Mechanism 
  - ✅ Forward Errors in MITM Mode
  - ✅ Provide Errors via MQTT

- Systems Information
  - :x: Operation duration
  - :x: Number of restarts
  - :x: Software Versions

- :x: Radio information

### Tasks

- [x] Check if these values are transferred from HMI to Main and locate these values transferred in the Serial protocol.
- [x] Update Protocol.md 
- [x] Parse values and provide them via MQTT
- [x] Analyze error listing functionality
- [x] Implement errors
- [x] Test

Work is done on seperate [branch](https://github.com/tspopp/AquaMQTT/tree/t/super_secret)
